// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProgramlamaVize.Data;

#nullable disable

namespace WebProgramlamaVize.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebProgramlamaVize.Models.Admin", b =>
                {
                    b.Property<int>("adminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adminId"));

                    b.Property<string>("adminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("adminId");

                    b.ToTable("Adminler");

                    b.HasData(
                        new
                        {
                            adminId = 1,
                            adminPassword = "12345",
                            adminUserName = "admin@gmail.com"
                        },
                        new
                        {
                            adminId = 2,
                            adminPassword = "12345",
                            adminUserName = "ilhan@gmail.com"
                        },
                        new
                        {
                            adminId = 3,
                            adminPassword = "12345",
                            adminUserName = "berk@gmail.com"
                        });
                });

            modelBuilder.Entity("WebProgramlamaVize.Models.Duyuru", b =>
                {
                    b.Property<int>("duyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("duyuruId"));

                    b.Property<string>("duyuruBaslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duyuruGorsel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duyuruIcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("duyuruTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("duyuruId");

                    b.ToTable("Duyurular");

                    b.HasData(
                        new
                        {
                            duyuruId = 1,
                            duyuruBaslik = "23 Kasım Düzce Depremi, Etkileri ve Normalleşme",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Üniversitemiz Deprem Uygulama ve Araştırma Merkezi tarafından düzenlenen “23 Kasım Düzce Depremi, Etkileri ve Normalleşme başlıklı program, Cumhuriyet Konferans Salonu’nda gerçekleştirildi.Konferansın konuşmacısı Üniversitemiz Deprem Uygulama ve Araştırma Merkezi Müdürü Doç. Dr. Mehmet Emin Arslan, 23 Kasım 2022 tarihinde 5,9 büyüklüğünde yaşanan depremde Düzce’nin, yapı stokunu yenilediği ve eski yapıları da güçlendirdiği için başarılı bir süreç geçirdiğini ifade etti. Çevre Şehircilik ve İklim Değişikliği Bakanlığı ile AFAD yetkilileriyle birlikte saha çalışmalarında bulunduğunu belirten Doç. Dr. Arslan, toptan göçme yaşanmadığını sözlerine ekledi.",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5083)
                        },
                        new
                        {
                            duyuruId = 2,
                            duyuruBaslik = "Öğretim Üyemizin Uluslararası Hakemli Tarih Dergisi TR Dizine Girdi",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Üniversitemiz Fen Edebiyat Fakültesi Tarih Bölümü Öğretim Üyesi Doç. Dr. Sabit Dokuyan’ın sahibi ve editörü olduğu “Journal of Universal History Studies” adlı uluslararası hakemli tarih dergi, TR Dizine girme başarısı gösterdi.Haziran ve Aralık aylarında olmak üzere yılda iki sayı olarak çıkarılan Journal of Universal History Studies’de Tarih ve Arkeoloji alanlarında çalışmalar yayınlanıyor.Yayınlanan tüm makalelere DOI numarasının atandığı dergi ile ilgili detaylı bilgilere https://dergipark.org.tr/tr/pub/juhis internet adresinden ulaşılabiliyor.",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5107)
                        },
                        new
                        {
                            duyuruId = 3,
                            duyuruBaslik = "Sanal İstihdam Fuarı",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Değerli Mensuplarımız,İstihdam Seferberliği kapsamında Türkiye’nin dört bir yanında gerçekleşen İstihdam Fuarları ve Kariyer Günleri oluşturulan “Sanal Fuar” teknolojisi ile daha global ve ulaşılabilir hale gelmektedir. Vatandaşlarımız,Sanal Fuar tarihlerinde https://sanalistihdamfuari.iskur.gov.tr adresine girerek, katılımcı firmalar ile yazılı veya görüntülü olarak görüşebilecek ve online olarak CV’ lerini bırakabileceklerdir.“Sanal Fuarı” ziyaret etmek isteyen vatandaşlarımızın izleyeceği adımlar şu şekildedir;1)Cep telefonu, bilgisayar veya tabletinizden https://sanalistihdamfuari.iskur.gov.tr adresine girin,2) Kayıt olun,3) Fuar tarihlerinde size gönderilen kullanıcı adı ve şifre ile giriş yapın,4) Profilinize önceden hazırladığınız CV’ yi yükleyin veya yeni CV oluşturun,5) Katılımcı firma yetkilileri ile görüşün, firmalar ve iş ve meslek danışmanları tarafından düzenlenecek seminerlere katılarak iş arama süreçleri ile işgücü piyasasına ilişkin bilgi düzeyinizi artırma imkanına sahip olun,6) İstediğiniz firmaya CV’nizi bırakın.Ayrıntılı bilgiye https://sanalistihdamfuari.iskur.gov.tr/login internet adresi üzerinden ulaşabilirsiniz.Bilgilerinize sunarız Düzce Üniversitesi Rektörlüğü",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5118)
                        },
                        new
                        {
                            duyuruId = 4,
                            duyuruBaslik = "Türkçe Yeterlik Sınavı",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Değerli Mensuplarımız,Yunus Emre Enstitüsü Başkanlığınca düzenlenen “Türkçe Yeterlik Sınavı (TYS)” bu yıl 14 Ocak 2023 tarihinde, sınav başvuruları 23 Kasım-21 Aralık 2022 tarihleri arasında yapılacak..",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5128)
                        },
                        new
                        {
                            duyuruId = 5,
                            duyuruBaslik = "Bölgesel Kalkınma Dergisi",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Değerli Mensuplarımız,T.C. Sanayi Bakanlığı Kalkınma Ajansları Genel Müdürlüğü tarafından yayımlanmakta olanBölgesel Kalkınma Dergisi” için makale gönderim işlemleri başlamıştır.Detaylı bilgiye htt... ",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5139)
                        },
                        new
                        {
                            duyuruId = 6,
                            duyuruBaslik = "Polis ve İletişim",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Üniversitemiz Gölyaka Meslek Yüksekokulu Halkla İlişkiler ve Tanıtım Programı'nda görevli Öğr. Gör. Nurgül Soydaş Düzce İl Emniyet Müdürlüğü Trafik Şube biriminde çalışan görevli tüm personele, ileti.",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5151)
                        },
                        new
                        {
                            duyuruId = 7,
                            duyuruBaslik = "Dijital İletişim Becerileri Anlatıldı",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Üniversitemiz Gölyaka Meslek Yüksekokulu Halkla İlişkiler ve Tanıtım Programı'nda görevli Öğr. Gör.Nurgül Soydaş, KTO Karatay Üniversitesi’nde “Dijital İletişim Becerileri” konulu seminer verdi.Konya...",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5202)
                        },
                        new
                        {
                            duyuruId = 8,
                            duyuruBaslik = "Eczacılık Fakültesi Uluslararası Ziyaretçi Konferansı 2022",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Eczacılık Fakültesi Uluslararası Ziyaretçi Konferansı ileri bir tarihe ertelenbiştir katılımcıların dikkatine...",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5212)
                        },
                        new
                        {
                            duyuruId = 9,
                            duyuruBaslik = "Türk Edebiyatı’nda İnsan Hakları Üzerine Bir Söyleşi",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Söyleşi online bir şekilde gerçekleştirilecektir detaylı açıklama önümüzdeki günlerde yapılacaktır.",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5222)
                        },
                        new
                        {
                            duyuruId = 10,
                            duyuruBaslik = "Bölgesel Kalkınma Dergisi",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Değerli Mensuplarımız,T.C. Sanayi Bakanlığı Kalkınma Ajansları Genel Müdürlüğü tarafından yayımlanmakta olan “Bölgesel Kalkınma Dergisi” için makale gönderim işlemleri başlamıştır.Detaylı bilgiye htt...",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5234)
                        },
                        new
                        {
                            duyuruId = 11,
                            duyuruBaslik = "3. Uluslararası Güvenlik Kongres",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Değerli Mensuplarımız,T.C. İçişleri Bakanlığı Jandarma ve Sahil Güvenlik Akademisi (JSGA) Başkanlığı tarafından suçla mücadelede bilimsel yöntem ve tekniklerin kullanılması temelinde birbirini tamamla...",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5244)
                        },
                        new
                        {
                            duyuruId = 12,
                            duyuruBaslik = "Mezun Öğrenci Takip Sistemi",
                            duyuruGorsel = "img/DUYURU.png",
                            duyuruIcerik = "Değerli Mensuplarımız,Akdeniz Üniversitesi Eğitim Fakültesi tarafından yürütülen kalite akreditasyon çalışmaları kapsamında \"Mezun Öğrenci Takip Sistemi\"nin kurulduğu belirtilmektedir.Mezun Öğrenci Ta...",
                            duyuruTarih = new DateTime(2022, 12, 12, 19, 31, 15, 116, DateTimeKind.Local).AddTicks(5254)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
